from google.adk import Agent
from problem_solver.triz_solver import triz_solver
from problem_solver.alternative_solver import alternative_solver
from pydantic import BaseModel, Field
from typing import List, Optional

# Define the structured output schema for the orchestrator
class TrizSolution(BaseModel):
    principle_id: int = Field(description="The numeric ID of the TRIZ Inventive Principle (1-40)")
    principle_name: str = Field(description="The name of the TRIZ Inventive Principle")
    solution_name: str = Field(description="A short name for the proposed solution")
    description: str = Field(description="A detailed description of how this principle solves the contradiction")

class AlternativeSolution(BaseModel):
    solution_name: str = Field(description="A short name for the proposed engineering solution")
    description: str = Field(description="A detailed description of the solution based on First Principles or standard patterns")

class DecisionMatrixRow(BaseModel):
    solution_name: str = Field(description="Name of the solution")
    score_a: int = Field(description="Score for Parameter A (1-5)")
    score_b: int = Field(description="Score for Parameter B (1-5)")
    wsi: float = Field(description="Weighted Suitability Index: (0.60 * score_a) + (0.40 * score_b)")
    rank: int = Field(description="Rank of the solution based on WSI (1 to 6)")

class DecisionMatrix(BaseModel):
    parameter_a: str = Field(description="Name of Parameter A (Goal/Value to maximize)")
    parameter_b: str = Field(description="Name of Parameter B (Cost/Constraint to minimize)")
    rows: List[DecisionMatrixRow] = Field(description="Matrix evaluation rows for all 6 solutions")

class ProblemSolverOutput(BaseModel):
    triz_solutions: List[TrizSolution] = Field(description="The 3 inventive solutions generated based on TRIZ principles")
    alternative_solutions: List[AlternativeSolution] = Field(description="The 3 architectural/engineering solutions generated by alternative_solver")
    decision_matrix: DecisionMatrix = Field(description="The dynamic decision matrix scoring all 6 solutions")
    scoring_justifications: List[str] = Field(description="Bulleted justifications for each score assigned in the matrix")
    master_evaluation_synthesis: str = Field(description="Master comparison, pros/cons, and final recommendation")

# Define the Master Orchestrator Agent (Exposed as the entry point)
root_agent = Agent(
    model="gemini-3.5-flash",
    name="root_agent",
    output_schema=ProblemSolverOutput,
    instruction=(
        "You are BuildWithAI, the Master Architect and Orchestrator.\n\n"
        "Your goal is to solve the user's contradiction by coordinating two specialized sub-agents:\n"
        "1. triz_solver: Generates 3 solutions based on classical TRIZ principles.\n"
        "2. alternative_solver: Generates 3 solutions based on general engineering patterns and First Principles.\n\n"
        "When a user presents a problem, you MUST perform the following workflow:\n"
        "1. Identify the core contradiction and dynamically extract the two competing parameters at play:\n"
        "   - Parameter A (Goal/Value, Weight = 0.60): What parameter/quality the user wants to optimize or maximize.\n"
        "   - Parameter B (Cost/Constraint, Weight = 0.40): The resource constraint or complexity cost we want to minimize.\n"
        "2. Delegate to the `triz_solver` sub-agent using the `transfer_to_agent` tool to get the 3 best TRIZ solutions. Do not try to solve the TRIZ part yourself.\n"
        "3. Delegate to the `alternative_solver` sub-agent using the `transfer_to_agent` tool to get the 3 best standard engineering patterns. Do not try to generate these patterns yourself.\n"
        "4. Evaluate all 6 solutions mathematically by grading them from 1 (poor) to 5 (excellent) on both dynamic parameters:\n"
        "   - Note: For Parameter B (Cost/Constraint), a score of 5 means 'extremely low cost/complexity' (excellent), and 1 means 'very high cost/complexity' (poor).\n"
        "   - Calculate: WSI = (0.60 * Parameter A Score) + (0.40 * Parameter B Score)\n\n"
        "Synthesize all recommendations and evaluations into the structured response schema format."
    ),
    sub_agents=[
        triz_solver,
        alternative_solver
    ]
)

