from pydantic import BaseModel, Field, model_validator
from typing import List

class TrizSolution(BaseModel):
    principle_id: int = Field(description="The numeric ID of the TRIZ Inventive Principle (1-40)")
    principle_name: str = Field(description="The name of the TRIZ Inventive Principle")
    solution_name: str = Field(description="A short name for the proposed solution")
    description: str = Field(description="A detailed description of how this principle solves the contradiction")

class TrizSpecialistOutput(BaseModel):
    solutions: List[TrizSolution] = Field(description="The 3 inventive solutions generated based on TRIZ principles")

class AlternativeSolution(BaseModel):
    solution_name: str = Field(description="A short name for the proposed engineering solution")
    description: str = Field(description="A detailed description of the solution based on First Principles or standard patterns")

class AlternativeSpecialistOutput(BaseModel):
    solutions: List[AlternativeSolution] = Field(description="The 3 architectural/engineering solutions generated by alternative_solver")

class DecisionMatrixRow(BaseModel):
    solution_name: str = Field(description="Name of the solution")
    score_a: int = Field(description="Score for Parameter A (1-5)")
    score_b: int = Field(description="Score for Parameter B (1-5)")
    wsi: float = Field(default=0.0, description="Weighted Suitability Index: (0.60 * score_a) + (0.40 * score_b)")
    rank: int = Field(default=0, description="Rank of the solution based on WSI (1 to 6)")

class DecisionMatrix(BaseModel):
    parameter_a: str = Field(description="Name of Parameter A (Goal/Value to maximize)")
    parameter_b: str = Field(description="Name of Parameter B (Cost/Constraint to minimize)")
    rows: List[DecisionMatrixRow] = Field(description="Matrix evaluation rows for all 6 solutions")

class ProblemSolverOutput(BaseModel):
    triz_solutions: List[TrizSolution] = Field(description="The 3 inventive solutions generated based on TRIZ principles")
    alternative_solutions: List[AlternativeSolution] = Field(description="The 3 architectural/engineering solutions generated by alternative_solver")
    decision_matrix: DecisionMatrix = Field(description="The dynamic decision matrix scoring all 6 solutions")
    scoring_justifications: List[str] = Field(description="Bulleted justifications for each score assigned in the matrix")
    master_evaluation_synthesis: str = Field(description="Master comparison, pros/cons, and final recommendation")

    @model_validator(mode="after")
    def calculate_wsi_and_ranks(self) -> "ProblemSolverOutput":
        # 1. Calculate WSI for each row
        for row in self.decision_matrix.rows:
            row.wsi = round((0.60 * row.score_a) + (0.40 * row.score_b), 2)
        
        # 2. Sort rows by WSI descending and assign ranks
        self.decision_matrix.rows.sort(key=lambda x: x.wsi, reverse=True)
        for i, row in enumerate(self.decision_matrix.rows):
            row.rank = i + 1
            
        return self
